<?php

namespace Clapit\Entity;

use Clapit\Helper\ClapitHelpers;

use Doctrine\ORM\EntityRepository;

/**
 * DealRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DealRepository extends EntityRepository
{

    /**
     * Find all active deal (deal we can participate on)
     *
     * @return array
     */
    public function findActive()
    {
        return $this
            ->createQueryBuilder('d')
            ->innerJoin('d.pdvs', 'pdv')
            ->innerJoin('d.url', 'u')
            ->where('d.dateLancement <= :currentDate')
            ->andWhere('d.dateFin >= :currentDate')
            ->andWhere('u.visible = true')
            ->setParameter('currentDate', date("Y-m-d H:i:s"))
            ->setMaxResults(10)
            ->orderBy('d.level', 'DESC')
            ->orderBy('d.dateLancement', 'ASC')
            ->getQuery()
            ->getResult()
        ;
    }
    
    /**
     * Find all passed (not ative) deal
     *
     * @return array
     */
    public function findNotActive()
    {
        return $this
            ->createQueryBuilder('d')
            ->innerJoin('d.winners', 'w')
            ->setMaxResults(40)
            ->groupBy('w.deal')
            ->orderBy('w.date', 'ASC')
            ->getQuery()
            ->getResult()
        ;
    }
}