<?php

namespace Clapit\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PdvRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PdvRepository extends EntityRepository
{

}